version: '3'

services:
  frontend:
    build: ./frontend
    container_name: rnp-front
    command: serve -s build -l 3000
    restart: unless-stopped
    # ports:
      # - "3000:3000"
    networks:
      - rnp

  api:
    build: ./api
    container_name: rnp-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://example.com
      - MONGO_URL=mongodb://db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - db
    networks:
      - rnp

  db:
    image: mongo:latest
    container_name: rnp-mongo
    volumes:
      - mongodb_api:/data/db
    networks:
      - rnp

  auth:
    build: ./auth
    container_name: rnp-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://example.com
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - rnp

  auth_db:
    image: mongo
    container_name: rnp-mongo-auth
    volumes:
      - mongodb_auth:/data/db
    networks:
      - rnp

  nginx:
    image: nginx:stable-alpine
    container_name: rnp-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - rnp

volumes:
  mongodb_api:
  mongodb_auth:

networks:
  rnp:
    driver: bridge