version: '3.1'

services:

  db:
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    # volumes:
      # - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080